[2024-08-24T20:05:22.767+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T20:05:22.785+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task manual__2024-08-24T20:05:17.921831+00:00 [queued]>
[2024-08-24T20:05:22.796+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task manual__2024-08-24T20:05:17.921831+00:00 [queued]>
[2024-08-24T20:05:22.797+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T20:05:22.815+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-08-24 20:05:17.921831+00:00
[2024-08-24T20:05:22.820+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T20:05:22.822+0000] {standard_task_runner.py:72} INFO - Started process 6634 to run task
[2024-08-24T20:05:22.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'manual__2024-08-24T20:05:17.921831+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpqu6775ir']
[2024-08-24T20:05:22.827+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask second_task
[2024-08-24T20:05:22.870+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v5.second_task manual__2024-08-24T20:05:17.921831+00:00 [running]> on host 90ca7eb2d7b6
[2024-08-24T20:05:22.955+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shreyas' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T20:05:17.921831+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T20:05:17.921831+00:00'
[2024-08-24T20:05:22.956+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T20:05:22.969+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-24T20:05:22.970+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, second task running after task1']
[2024-08-24T20:05:22.979+0000] {subprocess.py:86} INFO - Output:
[2024-08-24T20:05:22.980+0000] {subprocess.py:93} INFO - hey, second task running after task1
[2024-08-24T20:05:22.981+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-24T20:05:23.009+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T20:05:23.010+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, run_id=manual__2024-08-24T20:05:17.921831+00:00, execution_date=20240824T200517, start_date=20240824T200522, end_date=20240824T200523
[2024-08-24T20:05:23.037+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-24T20:05:23.056+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T20:05:23.059+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
