[2024-08-24T20:05:21.347+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T20:05:21.372+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task manual__2024-08-24T20:05:14.807630+00:00 [queued]>
[2024-08-24T20:05:21.383+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task manual__2024-08-24T20:05:14.807630+00:00 [queued]>
[2024-08-24T20:05:21.384+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T20:05:21.402+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): third_task> on 2024-08-24 20:05:14.807630+00:00
[2024-08-24T20:05:21.407+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6614) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T20:05:21.409+0000] {standard_task_runner.py:72} INFO - Started process 6625 to run task
[2024-08-24T20:05:21.409+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'third_task', 'manual__2024-08-24T20:05:14.807630+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpatja076t']
[2024-08-24T20:05:21.410+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask third_task
[2024-08-24T20:05:21.454+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v5.third_task manual__2024-08-24T20:05:14.807630+00:00 [running]> on host 90ca7eb2d7b6
[2024-08-24T20:05:21.542+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shreyas' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T20:05:14.807630+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T20:05:14.807630+00:00'
[2024-08-24T20:05:21.544+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T20:05:21.569+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-24T20:05:21.571+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, third task running after task1 at the same time as task2']
[2024-08-24T20:05:21.581+0000] {subprocess.py:86} INFO - Output:
[2024-08-24T20:05:21.583+0000] {subprocess.py:93} INFO - hey, third task running after task1 at the same time as task2
[2024-08-24T20:05:21.584+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-24T20:05:21.636+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T20:05:21.637+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=third_task, run_id=manual__2024-08-24T20:05:14.807630+00:00, execution_date=20240824T200514, start_date=20240824T200521, end_date=20240824T200521
[2024-08-24T20:05:21.669+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-24T20:05:21.688+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T20:05:21.691+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
